# Basic Tensor operations

In [1]:
import torch

In [2]:
torch.__version__

'2.10.0'

check if GPU is available

In [4]:
torch.cuda.is_available()

False

Tesnsors 
- A tensor is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions, acting as a container for data in n-dimensions

In [8]:
create_tensor = torch.tensor([1, 2, 3])
print(create_tensor)
create_tensor.dtype

tensor([1, 2, 3])


torch.int64

In [7]:
create_tensor = torch.tensor([1, 2, 3],dtype=torch.float32)
print(create_tensor)
create_tensor.dtype

tensor([1., 2., 3.])


torch.float32

In [20]:
#random tensor
torch.rand(3, 4)

tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])

In [23]:
# stop update random tensor
torch.manual_seed(42)
torch.rand(3, 4)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [24]:
torch.manual_seed(42)
torch.rand(3, 4)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Both Random tensors are same no furter updates on manual_seed 42

In [27]:
# 2 D tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

numpy like operations

In [28]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [31]:
torch.linspace(0,10,steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [32]:
torch.empty(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
torch.add(torch.ones(3,3),torch.eye(3))

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [ ]:
torch.mul(torch.ones(3,3),torch.eye(3)) # element wise multiplication

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.matmul(torch.ones(3,3),torch.eye(3,3)) # matrix multiplication

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.matmul(torch.ones(2,3),torch.eye(3,3)) # matrix multiplication with non square matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x = torch.ones(3,4)
y = torch.zeros_like(x) # dimensions like x 

In [64]:
print('x = ',x)
print('y = ',y)

x =  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
y =  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [65]:
x.to(dtype= torch.int32)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [67]:
torch.mean(torch.tensor([1,2,3,4],dtype=torch.float32))

tensor(2.5000)

In [68]:
torch.median(torch.tensor([1,2,3,4],dtype=torch.float32))

tensor(2.)

In [71]:
torch.mode(torch.tensor([1,2,4,4],dtype=torch.float32))

torch.return_types.mode(
values=tensor(4.),
indices=tensor(3))

In [ ]:
torch.argmax(torch.tensor([1,2,4,4],dtype=torch.float32)) # index of max value

tensor(2)

In [ ]:
torch.argmin(torch.tensor([1,2,4,4],dtype=torch.float32)) # index of min value

tensor(0)